openapi: '3.0.3'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://localhost:8080
    description: Local server for testing
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
